add job order note

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -9,6 +9,10 @@
 # And "kubernetes-env" for everything else. Please mention "image:" container name to be used
 # with it, as there's no default one.
 
+# All jobs are sorted according to their duration using DAG mechanism
+# Currently, test-linux-stable job is the longest one and other jobs are
+# sorted in order to complete during this job and occupy less runners in one
+# moment of time.
 stages:
   - stage1
   - stage2
@@ -153,6 +157,39 @@ default:
       vault:                       cicd/gitlab/$CI_PROJECT_PATH/REL_MAN_ROOM_ID@kv
       file:                        false
 
+.build-push-image:                 &build-push-image
+  <<:                              *kubernetes-env
+  image:                           quay.io/buildah/stable
+  variables:                       &image-variables
+    GIT_STRATEGY:                  none
+    DOCKER_USER:                   ${PARITYPR_USER}
+    DOCKER_PASS:                   ${PARITYPR_PASS}
+  before_script:                   &check-versions
+    - test -s ./artifacts/VERSION || exit 1
+    - test -s ./artifacts/EXTRATAG || exit 1
+    - VERSION="$(cat ./artifacts/VERSION)"
+    - EXTRATAG="$(cat ./artifacts/EXTRATAG)"
+    - echo "Polkadot version = ${VERSION} (EXTRATAG = ${EXTRATAG})"
+  script:
+    - test "$DOCKER_USER" -a "$DOCKER_PASS" ||
+        ( echo "no docker credentials provided"; exit 1 )
+    - cd ./artifacts
+    - buildah bud
+        --format=docker
+        --build-arg VCS_REF="${CI_COMMIT_SHA}"
+        --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
+        --build-arg IMAGE_NAME="${IMAGE_NAME}"
+        --tag "$IMAGE_NAME:$VERSION"
+        --tag "$IMAGE_NAME:$EXTRATAG"
+        --file ${DOCKERFILE} .
+    # The job will success only on the protected branch
+    - echo "$DOCKER_PASS" |
+        buildah login --username "$DOCKER_USER" --password-stdin docker.io
+    - buildah info
+    - buildah push --format=v2s2 "$IMAGE_NAME:$VERSION"
+    - buildah push --format=v2s2 "$IMAGE_NAME:$EXTRATAG"
+  after_script:
+    - buildah logout --all
 
 #### stage:                        stage1
 
@@ -241,16 +278,19 @@ cargo-fmt:
     - cargo +nightly fmt --all -- --check
   allow_failure:                   true
 
-test-deterministic-wasm:
-  stage:                           stage2
-  <<:                              *test-refs
+spellcheck:
+  stage:                           stage1
   <<:                              *docker-env
-  <<:                              *compiler-info
-  needs:
-    - job:                         spellcheck
-      artifacts:                   false
+  <<:                              *test-refs
   script:
-    - ./scripts/gitlab/test_deterministic_wasm.sh
+    - cargo spellcheck --version
+    # compare with the commit parent to the PR, given it's from a default branch
+    - git fetch origin +${CI_DEFAULT_BRANCH}:${CI_DEFAULT_BRANCH}
+    - echo "___Spellcheck is going to check your diff___"
+    - cargo spellcheck list-files -vvv $(git diff --diff-filter=AM --name-only $(git merge-base ${CI_COMMIT_SHA} ${CI_DEFAULT_BRANCH} -- :^bridges))
+    - time cargo spellcheck check -vvv --cfg=scripts/gitlab/spellcheck.toml --checkers hunspell --code 1
+        $(git diff --diff-filter=AM --name-only $(git merge-base ${CI_COMMIT_SHA} ${CI_DEFAULT_BRANCH} -- :^bridges))
+  allow_failure:                   true
 
 test-linux-stable:
   stage:                           stage1
@@ -265,6 +305,19 @@ test-linux-stable:
   script:
     # Builds with the runtime benchmarks/metrics features are only to be used for testing.
     - time cargo test --workspace --profile testnet --verbose --locked --features=runtime-benchmarks,runtime-metrics
+
+#### stage:                        stage2
+
+test-deterministic-wasm:
+  stage:                           stage2
+  <<:                              *test-refs
+  <<:                              *docker-env
+  <<:                              *compiler-info
+  needs:
+    - job:                         spellcheck
+      artifacts:                   false
+  script:
+    - ./scripts/gitlab/test_deterministic_wasm.sh
 
 test-node-metrics:
   stage:                           stage2
@@ -284,63 +337,6 @@ test-node-metrics:
     # `runtime_can_publish_metrics` test uses the `test-runtime` which doesn't support
     # the `runtime-benchmarks` feature.
     - time cargo test  --profile testnet --verbose --locked --features=runtime-metrics -p polkadot-node-metrics
-
-
-check-runtime-benchmarks:
-  stage:                           stage3
-  <<:                              *test-refs
-  <<:                              *docker-env
-  <<:                              *compiler-info
-  needs:
-    - job:                         test-node-metrics
-      artifacts:                   false
-  script:
-    # Check that everything compiles with `runtime-benchmarks` feature flag.
-    - cargo check --features runtime-benchmarks --all
-    - sccache -s
-
-check-try-runtime:
-  stage:                           stage3
-  <<:                              *test-refs
-  <<:                              *docker-env
-  <<:                              *compiler-info
-  needs:
-    - job:                         test-node-metrics
-      artifacts:                   false
-  script:
-    # Check that everything compiles with `try-runtime` feature flag.
-    - cargo check --features try-runtime --all
-    - sccache -s
-
-check-no-default-features:
-  stage:                           stage3
-  <<:                              *test-refs
-  <<:                              *docker-env
-  <<:                              *compiler-info
-  needs:
-    - job:                         test-deterministic-wasm
-      artifacts:                   false
-  script:
-    # Check that polkadot-cli will compile no default features.
-    - pushd node/service && cargo check --no-default-features && popd
-    - pushd cli && cargo check --no-default-features --features "service" && popd
-    - sccache -s
-
-spellcheck:
-  stage:                           stage1
-  <<:                              *docker-env
-  <<:                              *test-refs
-  script:
-    - cargo spellcheck --version
-    # compare with the commit parent to the PR, given it's from a default branch
-    - git fetch origin +${CI_DEFAULT_BRANCH}:${CI_DEFAULT_BRANCH}
-    - echo "___Spellcheck is going to check your diff___"
-    - cargo spellcheck list-files -vvv $(git diff --diff-filter=AM --name-only $(git merge-base ${CI_COMMIT_SHA} ${CI_DEFAULT_BRANCH} -- :^bridges))
-    - time cargo spellcheck check -vvv --cfg=scripts/gitlab/spellcheck.toml --checkers hunspell --code 1
-        $(git diff --diff-filter=AM --name-only $(git merge-base ${CI_COMMIT_SHA} ${CI_DEFAULT_BRANCH} -- :^bridges))
-  allow_failure:                   true
-
-
 
 .check-dependent-project:          &check-dependent-project
   stage:                           stage2
@@ -368,9 +364,6 @@ check-dependent-cumulus:
     DEPENDENT_REPO: cumulus
     CARGO_UPDATE_CRATES: "sp-io polkadot-runtime-common"
 
-#### stage:                        build
-
-
 check-transaction-versions:
   stage:                           stage2
   <<:                              *test-refs
@@ -387,78 +380,6 @@ check-transaction-versions:
     - git fetch origin release
   script:
     - scripts/gitlab/check_extrinsics_ordering.sh
-
-generate-impl-guide:
-  stage:                           stage3
-  <<:                              *test-refs
-  <<:                              *docker-env
-  needs:
-    - job:                         check-transaction-versions
-      artifacts:                   false
-  image:
-    name: michaelfbryan/mdbook-docker-image:v0.4.4
-    entrypoint: [""]
-  script:
-    - mdbook build roadmap/implementers-guide
-
-build-rustdoc:
-  stage:                           stage3
-  <<:                              *docker-env
-  <<:                              *test-refs
-  needs:
-    - job:                         test-deterministic-wasm
-      artifacts:                   false
-  variables:
-    SKIP_WASM_BUILD:               1
-  artifacts:
-    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}-doc"
-    when:                          on_success
-    expire_in:                     7 days
-    paths:
-    - ./crate-docs/
-  script:
-    # FIXME: it fails with `RUSTDOCFLAGS="-Dwarnings"` and `--all-features`
-    - time cargo doc --workspace --verbose
-    - rm -f ./target/doc/.lock
-    - mv ./target/doc ./crate-docs
-    # FIXME: remove me after CI image gets nonroot
-    - chown -R nonroot:nonroot ./crate-docs
-    - echo "<meta http-equiv=refresh content=0;url=polkadot_service/index.html>" > ./crate-docs/index.html
-    - sccache -s
-
-.build-push-image:                 &build-push-image
-  <<:                              *kubernetes-env
-  image:                           quay.io/buildah/stable
-  variables:                       &image-variables
-    GIT_STRATEGY:                  none
-    DOCKER_USER:                   ${PARITYPR_USER}
-    DOCKER_PASS:                   ${PARITYPR_PASS}
-  before_script:                   &check-versions
-    - test -s ./artifacts/VERSION || exit 1
-    - test -s ./artifacts/EXTRATAG || exit 1
-    - VERSION="$(cat ./artifacts/VERSION)"
-    - EXTRATAG="$(cat ./artifacts/EXTRATAG)"
-    - echo "Polkadot version = ${VERSION} (EXTRATAG = ${EXTRATAG})"
-  script:
-    - test "$DOCKER_USER" -a "$DOCKER_PASS" ||
-        ( echo "no docker credentials provided"; exit 1 )
-    - cd ./artifacts
-    - buildah bud
-        --format=docker
-        --build-arg VCS_REF="${CI_COMMIT_SHA}"
-        --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
-        --build-arg IMAGE_NAME="${IMAGE_NAME}"
-        --tag "$IMAGE_NAME:$VERSION"
-        --tag "$IMAGE_NAME:$EXTRATAG"
-        --file ${DOCKERFILE} .
-    # The job will success only on the protected branch
-    - echo "$DOCKER_PASS" |
-        buildah login --username "$DOCKER_USER" --password-stdin docker.io
-    - buildah info
-    - buildah push --format=v2s2 "$IMAGE_NAME:$VERSION"
-    - buildah push --format=v2s2 "$IMAGE_NAME:$EXTRATAG"
-  after_script:
-    - buildah logout --all
 
 publish-polkadot-image:
   stage:                           stage2
@@ -562,8 +483,6 @@ update_westend_weights:
   variables:
     RUNTIME:                       westend
 
-#### stage:                        publish
-
 publish-s3-release:                &publish-s3
   stage:                           stage2
   needs:
@@ -605,56 +524,85 @@ publish-s3-release:                &publish-s3
     - aws s3 ls s3://${AWS_BUCKET}/${PREFIX}/${EXTRATAG}/
         --recursive --human-readable --summarize
 
-publish-rustdoc:
-  stage:                           stage4
-  <<:                              *kubernetes-env
-  <<:                              *vault-secrets
-  image:                           paritytech/tools:latest
-  variables:
-    GIT_DEPTH:                     100
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "pipeline"
-      when: never
-    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME == "master"
-    - if: $CI_COMMIT_REF_NAME == "master"
-  # `needs:` can be removed after CI image gets nonroot. In this case `needs:` stops other
-  # artifacts from being dowloaded by this job.
-  needs:
-    - job:                         build-rustdoc
-      artifacts:                   true
-  script:
-    # setup ssh
-    - eval $(ssh-agent)
-    - ssh-add - <<< ${GITHUB_SSH_PRIV_KEY}
-    - mkdir ~/.ssh && touch ~/.ssh/known_hosts
-    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
-    # Set git config
-    - git config user.email "devops-team@parity.io"
-    - git config user.name "${GITHUB_USER}"
-    - git config remote.origin.url "git@github.com:/paritytech/${CI_PROJECT_NAME}.git"
-    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
-    - git fetch origin gh-pages
-    # Save README and docs
-    - cp -r ./crate-docs/ /tmp/doc/
-    - cp README.md /tmp/doc/
-    - git checkout gh-pages
-    # Remove everything and restore generated docs and README
-    - rm -rf ./*
-    - mv /tmp/doc/* .
-    # Upload files
-    - git add --all --force
-    # `git commit` has an exit code of > 0 if there is nothing to commit.
-    # This causes GitLab to exit immediately and marks this job failed.
-    # We don't want to mark the entire job failed if there's nothing to
-    # publish though, hence the `|| true`.
-    - git commit -m "Updated docs for ${CI_COMMIT_REF_NAME}" ||
-        echo "___Nothing to commit___"
-    - git push origin gh-pages --force
-    - echo "___Rustdoc was successfully published to https://paritytech.github.io/polkadot/___"
-  after_script:
-    - rm -rf .git/ ./*
+#### stage:                        stage3
 
-#### stage:                        deploy
+check-runtime-benchmarks:
+  stage:                           stage3
+  <<:                              *test-refs
+  <<:                              *docker-env
+  <<:                              *compiler-info
+  needs:
+    - job:                         test-node-metrics
+      artifacts:                   false
+  script:
+    # Check that everything compiles with `runtime-benchmarks` feature flag.
+    - cargo check --features runtime-benchmarks --all
+    - sccache -s
+
+check-try-runtime:
+  stage:                           stage3
+  <<:                              *test-refs
+  <<:                              *docker-env
+  <<:                              *compiler-info
+  needs:
+    - job:                         test-node-metrics
+      artifacts:                   false
+  script:
+    # Check that everything compiles with `try-runtime` feature flag.
+    - cargo check --features try-runtime --all
+    - sccache -s
+
+check-no-default-features:
+  stage:                           stage3
+  <<:                              *test-refs
+  <<:                              *docker-env
+  <<:                              *compiler-info
+  needs:
+    - job:                         test-deterministic-wasm
+      artifacts:                   false
+  script:
+    # Check that polkadot-cli will compile no default features.
+    - pushd node/service && cargo check --no-default-features && popd
+    - pushd cli && cargo check --no-default-features --features "service" && popd
+    - sccache -s
+
+generate-impl-guide:
+  stage:                           stage3
+  <<:                              *test-refs
+  <<:                              *docker-env
+  needs:
+    - job:                         check-transaction-versions
+      artifacts:                   false
+  image:
+    name: michaelfbryan/mdbook-docker-image:v0.4.4
+    entrypoint: [""]
+  script:
+    - mdbook build roadmap/implementers-guide
+
+build-rustdoc:
+  stage:                           stage3
+  <<:                              *docker-env
+  <<:                              *test-refs
+  needs:
+    - job:                         test-deterministic-wasm
+      artifacts:                   false
+  variables:
+    SKIP_WASM_BUILD:               1
+  artifacts:
+    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}-doc"
+    when:                          on_success
+    expire_in:                     7 days
+    paths:
+    - ./crate-docs/
+  script:
+    # FIXME: it fails with `RUSTDOCFLAGS="-Dwarnings"` and `--all-features`
+    - time cargo doc --workspace --verbose
+    - rm -f ./target/doc/.lock
+    - mv ./target/doc ./crate-docs
+    # FIXME: remove me after CI image gets nonroot
+    - chown -R nonroot:nonroot ./crate-docs
+    - echo "<meta http-equiv=refresh content=0;url=polkadot_service/index.html>" > ./crate-docs/index.html
+    - sccache -s
 
 deploy-parity-testnet:
   stage:                           stage3
@@ -724,3 +672,56 @@ zombienet-tests-malus-dispute-valid:
   retry: 2
   tags:
     - zombienet-polkadot-integration-test
+
+
+
+#### stage:                        stage4
+
+publish-rustdoc:
+  stage:                           stage4
+  <<:                              *kubernetes-env
+  <<:                              *vault-secrets
+  image:                           paritytech/tools:latest
+  variables:
+    GIT_DEPTH:                     100
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "pipeline"
+      when: never
+    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME == "master"
+    - if: $CI_COMMIT_REF_NAME == "master"
+  # `needs:` can be removed after CI image gets nonroot. In this case `needs:` stops other
+  # artifacts from being dowloaded by this job.
+  needs:
+    - job:                         build-rustdoc
+      artifacts:                   true
+  script:
+    # setup ssh
+    - eval $(ssh-agent)
+    - ssh-add - <<< ${GITHUB_SSH_PRIV_KEY}
+    - mkdir ~/.ssh && touch ~/.ssh/known_hosts
+    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
+    # Set git config
+    - git config user.email "devops-team@parity.io"
+    - git config user.name "${GITHUB_USER}"
+    - git config remote.origin.url "git@github.com:/paritytech/${CI_PROJECT_NAME}.git"
+    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+    - git fetch origin gh-pages
+    # Save README and docs
+    - cp -r ./crate-docs/ /tmp/doc/
+    - cp README.md /tmp/doc/
+    - git checkout gh-pages
+    # Remove everything and restore generated docs and README
+    - rm -rf ./*
+    - mv /tmp/doc/* .
+    # Upload files
+    - git add --all --force
+    # `git commit` has an exit code of > 0 if there is nothing to commit.
+    # This causes GitLab to exit immediately and marks this job failed.
+    # We don't want to mark the entire job failed if there's nothing to
+    # publish though, hence the `|| true`.
+    - git commit -m "Updated docs for ${CI_COMMIT_REF_NAME}" ||
+        echo "___Nothing to commit___"
+    - git push origin gh-pages --force
+    - echo "___Rustdoc was successfully published to https://paritytech.github.io/polkadot/___"
+  after_script:
+    - rm -rf .git/ ./*
