trigger 13: no nufin

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -23,235 +23,235 @@ image:                             paritytech/ci-linux:production
 #     - if: $CI_COMMIT_TAG
 #     - if: $CI_COMMIT_BRANCH
 
-variables:
-  GIT_STRATEGY:                    fetch
-  GIT_DEPTH:                       100
-  CI_SERVER_NAME:                  "GitLab CI"
-  DOCKER_OS:                       "debian:stretch"
-  ARCH:                            "x86_64"
+# variables:
+#   GIT_STRATEGY:                    fetch
+#   GIT_DEPTH:                       100
+#   CI_SERVER_NAME:                  "GitLab CI"
+#   DOCKER_OS:                       "debian:stretch"
+#   ARCH:                            "x86_64"
 
-default:
-  cache:                           {}
+# default:
+#   cache:                           {}
 
-.collect-artifacts:                &collect-artifacts
-  artifacts:
-    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
-    when:                          on_success
-    expire_in:                     28 days
-    paths:
-      - ./artifacts/
+# .collect-artifacts:                &collect-artifacts
+#   artifacts:
+#     name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
+#     when:                          on_success
+#     expire_in:                     28 days
+#     paths:
+#       - ./artifacts/
 
-.kubernetes-env:                   &kubernetes-env
-  tags:
-    - kubernetes-parity-build
-  interruptible:                   true
+# .kubernetes-env:                   &kubernetes-env
+#   tags:
+#     - kubernetes-parity-build
+#   interruptible:                   true
 
-.docker-env:                       &docker-env
-  retry:
-    max: 2
-    when:
-      - runner_system_failure
-      - unknown_failure
-      - api_failure
-  interruptible:                   true
-  tags:
-    - linux-docker
+# .docker-env:                       &docker-env
+#   retry:
+#     max: 2
+#     when:
+#       - runner_system_failure
+#       - unknown_failure
+#       - api_failure
+#   interruptible:                   true
+#   tags:
+#     - linux-docker
 
-.compiler-info:                    &compiler-info
-  before_script:
-    - rustup show
-    - cargo --version
-    - sccache -s
+# .compiler-info:                    &compiler-info
+#   before_script:
+#     - rustup show
+#     - cargo --version
+#     - sccache -s
 
-# .rules-test:                       &rules-test
-#   # these jobs run always*
-#   rules:
-#     - if: $CI_COMMIT_REF_NAME == "rococo-v1"
-#       when: never
-#     - when: always
+# # .rules-test:                       &rules-test
+# #   # these jobs run always*
+# #   rules:
+# #     - if: $CI_COMMIT_REF_NAME == "rococo-v1"
+# #       when: never
+# #     - when: always
 
-# .pr-only:                          &rules-pr-only
-#   # these jobs run only on PRs
-#   rules:
-#     - if: $CI_COMMIT_REF_NAME == "rococo-v1"
-#       when: never
-#     - if: $CI_PIPELINE_SOURCE == "schedule"
-#       when: never
-#     - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
+# # .pr-only:                          &rules-pr-only
+# #   # these jobs run only on PRs
+# #   rules:
+# #     - if: $CI_COMMIT_REF_NAME == "rococo-v1"
+# #       when: never
+# #     - if: $CI_PIPELINE_SOURCE == "schedule"
+# #       when: never
+# #     - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
 
-.pack-artifacts:                   &pack-artifacts
-  - mkdir -p ./artifacts
-  - VERSION="${CI_COMMIT_REF_NAME}" # will be tag or branch name
-  # - mv ./target/release/polkadot ./artifacts/.
-  # - sha256sum ./artifacts/polkadot | tee ./artifacts/polkadot.sha256
-  # - if [ "${CI_COMMIT_TAG}" ]; then
-  #     EXTRATAG="latest";
-  #   else
-  #     EXTRATAG="$(./artifacts/polkadot --version |
-  #       sed -n -r 's/^polkadot ([0-9.]+.*-[0-9a-f]{7,13})-.*$/\1/p')";
-  #     EXTRATAG="${CI_COMMIT_REF_NAME}-${EXTRATAG}-$(cut -c 1-8 ./artifacts/polkadot.sha256)";
-  #   fi
-  - EXTRATAG=debug-$CI_COMMIT_REF_NAME
-  - echo "Polkadot version = ${VERSION} (EXTRATAG = ${EXTRATAG})"
-  - echo -n ${VERSION} > ./artifacts/VERSION
-  - echo -n ${EXTRATAG} > ./artifacts/EXTRATAG
-  - cp -r scripts/docker/* ./artifacts
+# .pack-artifacts:                   &pack-artifacts
+#   - mkdir -p ./artifacts
+#   - VERSION="${CI_COMMIT_REF_NAME}" # will be tag or branch name
+#   # - mv ./target/release/polkadot ./artifacts/.
+#   # - sha256sum ./artifacts/polkadot | tee ./artifacts/polkadot.sha256
+#   # - if [ "${CI_COMMIT_TAG}" ]; then
+#   #     EXTRATAG="latest";
+#   #   else
+#   #     EXTRATAG="$(./artifacts/polkadot --version |
+#   #       sed -n -r 's/^polkadot ([0-9.]+.*-[0-9a-f]{7,13})-.*$/\1/p')";
+#   #     EXTRATAG="${CI_COMMIT_REF_NAME}-${EXTRATAG}-$(cut -c 1-8 ./artifacts/polkadot.sha256)";
+#   #   fi
+#   - EXTRATAG=debug-$CI_COMMIT_REF_NAME
+#   - echo "Polkadot version = ${VERSION} (EXTRATAG = ${EXTRATAG})"
+#   - echo -n ${VERSION} > ./artifacts/VERSION
+#   - echo -n ${EXTRATAG} > ./artifacts/EXTRATAG
+#   - cp -r scripts/docker/* ./artifacts
 
-build-linux-release:
-  stage:                           test
-  <<:                              *collect-artifacts
-  <<:                              *docker-env
-  <<:                              *compiler-info
-  # rules:
-  #   - if: $CI_PIPELINE_SOURCE == "schedule"
-  #   - if: $CI_COMMIT_REF_NAME == "master"
-  #   - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
-  script:
-    # - time cargo build --release --verbose
-    # - sccache -s
-    - *pack-artifacts
+# build-linux-release:
+#   stage:                           test
+#   <<:                              *collect-artifacts
+#   <<:                              *docker-env
+#   <<:                              *compiler-info
+#   # rules:
+#   #   - if: $CI_PIPELINE_SOURCE == "schedule"
+#   #   - if: $CI_COMMIT_REF_NAME == "master"
+#   #   - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
+#   script:
+#     # - time cargo build --release --verbose
+#     # - sccache -s
+#     - *pack-artifacts
 
-build-real-overseer:
-  stage:                           test
-  <<:                              *collect-artifacts
-  <<:                              *docker-env
-  <<:                              *compiler-info
-  # rules:
-  #   - if: $CI_PIPELINE_SOURCE == "schedule"
-  #   - if: $CI_COMMIT_REF_NAME == "master"
-  #   - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
-  #   - if: $CI_COMMIT_REF_NAME == "rococo-v1"
-  script:
-    # - time cargo build --release --verbose --features=real-overseer
-    # - sccache -s
-    - *pack-artifacts
+# build-real-overseer:
+#   stage:                           test
+#   <<:                              *collect-artifacts
+#   <<:                              *docker-env
+#   <<:                              *compiler-info
+#   # rules:
+#   #   - if: $CI_PIPELINE_SOURCE == "schedule"
+#   #   - if: $CI_COMMIT_REF_NAME == "master"
+#   #   - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
+#   #   - if: $CI_COMMIT_REF_NAME == "rococo-v1"
+#   script:
+#     # - time cargo build --release --verbose --features=real-overseer
+#     # - sccache -s
+#     - *pack-artifacts
 
-build-adder-collator:
-  stage:                           test
-  <<:                              *collect-artifacts
-  <<:                              *docker-env
-  <<:                              *compiler-info
-  # rules:
-  #   - if: $CI_PIPELINE_SOURCE == "schedule"
-  #   - if: $CI_COMMIT_REF_NAME == "master"
-  #   - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
-  script:
-    # - time cargo build --release --verbose --features=real-overseer -p test-parachain-adder-collator
-    # - sccache -s
-    # pack artifacts
-    - mkdir -p ./artifacts
-    # - mv ./target/release/adder-collator ./artifacts/.
-    - echo -n "${CI_COMMIT_REF_NAME}" > ./artifacts/VERSION
-    - echo -n "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}" > ./artifacts/EXTRATAG
-    - echo "adder-collator version = $(cat ./artifacts/VERSION) (EXTRATAG = $(cat ./artifacts/EXTRATAG))"
-    - cp -r scripts/docker/* ./artifacts
+# build-adder-collator:
+#   stage:                           test
+#   <<:                              *collect-artifacts
+#   <<:                              *docker-env
+#   <<:                              *compiler-info
+#   # rules:
+#   #   - if: $CI_PIPELINE_SOURCE == "schedule"
+#   #   - if: $CI_COMMIT_REF_NAME == "master"
+#   #   - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
+#   script:
+#     # - time cargo build --release --verbose --features=real-overseer -p test-parachain-adder-collator
+#     # - sccache -s
+#     # pack artifacts
+#     - mkdir -p ./artifacts
+#     # - mv ./target/release/adder-collator ./artifacts/.
+#     - echo -n "${CI_COMMIT_REF_NAME}" > ./artifacts/VERSION
+#     - echo -n "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}" > ./artifacts/EXTRATAG
+#     - echo "adder-collator version = $(cat ./artifacts/VERSION) (EXTRATAG = $(cat ./artifacts/EXTRATAG))"
+#     - cp -r scripts/docker/* ./artifacts
 
-#### stage:                        build
+# #### stage:                        build
 
-.build-push-image:                 &build-push-image
-  <<:                              *kubernetes-env
-  image:                           quay.io/buildah/stable
-  variables:
-    GIT_STRATEGY:                  none
-    # scripts/docker/Dockerfile
-    DOCKERFILE:                    Dockerfile
-    IMAGE_NAME:                    docker.io/parity/polkadot
-    DOCKER_USER:                   ${Docker_Hub_User_Parity}
-    DOCKER_PASS:                   ${Docker_Hub_Pass_Parity}
-  before_script:                   &check-versions
-    - test -s ./artifacts/VERSION || exit 1
-    - test -s ./artifacts/EXTRATAG || exit 1
-    - VERSION="$(cat ./artifacts/VERSION)"
-    - EXTRATAG="$(cat ./artifacts/EXTRATAG)"
-    - echo "Polkadot version = ${VERSION} (EXTRATAG ${EXTRATAG})"
-  script:
-    # - test "$DOCKER_USER" -a "$DOCKER_PASS" ||
-    #     ( echo "no docker credentials provided"; exit 1 )
-    # - cd ./artifacts
-    # - buildah bud
-    #     --format=docker
-    #     --build-arg VCS_REF="${CI_COMMIT_SHA}"
-    #     --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
-    #     --build-arg IMAGE_NAME="${IMAGE_NAME}"
-    #     --tag "$IMAGE_NAME:$VERSION"
-    #     --tag "$IMAGE_NAME:$EXTRATAG"
-    #     --file ${DOCKERFILE} .
-    # The job will success only on the protected branch
-    # - echo "$DOCKER_PASS" |
-    #     buildah login --username "$DOCKER_USER" --password-stdin docker.io
-    # - buildah info
-    # - buildah push --format=v2s2 "$IMAGE_NAME:$VERSION"
-    - echo 'buildah push --format=v2s2 "$IMAGE_NAME:$EXTRATAG"'
-  after_script:
-    # - buildah logout "$IMAGE_NAME"
-    # pass artifacts to the trigger-simnet job
-    - echo "IMAGE_NAME=${IMAGE_NAME}" > ./artifacts/overseer.env
-    - echo "IMAGE_TAG=$(cat ./artifacts/EXTRATAG)" >> ./artifacts/overseer.env
-    - cat ./artifacts/overseer.env
-  artifacts:
-    reports:
-      # this artifact is used in trigger-simnet job
-      # https://docs.gitlab.com/ee/ci/multi_project_pipelines.html#with-variable-inheritance
-      dotenv: ./artifacts/overseer.env
+# .build-push-image:                 &build-push-image
+#   <<:                              *kubernetes-env
+#   image:                           quay.io/buildah/stable
+#   variables:
+#     GIT_STRATEGY:                  none
+#     # scripts/docker/Dockerfile
+#     DOCKERFILE:                    Dockerfile
+#     IMAGE_NAME:                    docker.io/parity/polkadot
+#     DOCKER_USER:                   ${Docker_Hub_User_Parity}
+#     DOCKER_PASS:                   ${Docker_Hub_Pass_Parity}
+#   before_script:                   &check-versions
+#     - test -s ./artifacts/VERSION || exit 1
+#     - test -s ./artifacts/EXTRATAG || exit 1
+#     - VERSION="$(cat ./artifacts/VERSION)"
+#     - EXTRATAG="$(cat ./artifacts/EXTRATAG)"
+#     - echo "Polkadot version = ${VERSION} (EXTRATAG ${EXTRATAG})"
+#   script:
+#     # - test "$DOCKER_USER" -a "$DOCKER_PASS" ||
+#     #     ( echo "no docker credentials provided"; exit 1 )
+#     # - cd ./artifacts
+#     # - buildah bud
+#     #     --format=docker
+#     #     --build-arg VCS_REF="${CI_COMMIT_SHA}"
+#     #     --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
+#     #     --build-arg IMAGE_NAME="${IMAGE_NAME}"
+#     #     --tag "$IMAGE_NAME:$VERSION"
+#     #     --tag "$IMAGE_NAME:$EXTRATAG"
+#     #     --file ${DOCKERFILE} .
+#     # The job will success only on the protected branch
+#     # - echo "$DOCKER_PASS" |
+#     #     buildah login --username "$DOCKER_USER" --password-stdin docker.io
+#     # - buildah info
+#     # - buildah push --format=v2s2 "$IMAGE_NAME:$VERSION"
+#     - echo 'buildah push --format=v2s2 "$IMAGE_NAME:$EXTRATAG"'
+#   after_script:
+#     # - buildah logout "$IMAGE_NAME"
+#     # pass artifacts to the trigger-simnet job
+#     - echo "IMAGE_NAME=${IMAGE_NAME}" > ./artifacts/overseer.env
+#     - echo "IMAGE_TAG=$(cat ./artifacts/EXTRATAG)" >> ./artifacts/overseer.env
+#     - cat ./artifacts/overseer.env
+#   artifacts:
+#     reports:
+#       # this artifact is used in trigger-simnet job
+#       # https://docs.gitlab.com/ee/ci/multi_project_pipelines.html#with-variable-inheritance
+#       dotenv: ./artifacts/overseer.env
 
 
-publish-polkadot-image:
-  stage:                           build
-  <<:                              *build-push-image
-  # rules:
-  # # Don't run on releases - this is handled by the Github Action here:
-  # # .github/workflows/publish-docker-release.yml
-  #   - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
-  #     when: never
-  #   - if: $CI_PIPELINE_SOURCE == "schedule"
-  #   - if: $CI_COMMIT_REF_NAME == "master"
-  # needs:
-  #   - job:                         build-linux-release
-  #     artifacts:                   true
+# publish-polkadot-image:
+#   stage:                           build
+#   <<:                              *build-push-image
+#   # rules:
+#   # # Don't run on releases - this is handled by the Github Action here:
+#   # # .github/workflows/publish-docker-release.yml
+#   #   - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
+#   #     when: never
+#   #   - if: $CI_PIPELINE_SOURCE == "schedule"
+#   #   - if: $CI_COMMIT_REF_NAME == "master"
+#   # needs:
+#   #   - job:                         build-linux-release
+#   #     artifacts:                   true
 
-publish-real-overseer-image:
-#   image to be tested with Simnet
-  stage:                           build
-  <<:                              *build-push-image
-  variables:
-    IMAGE_NAME:                    docker.io/paritypr/synth-wave
-    DOCKER_USER:                   ${PARITYPR_USER}
-    DOCKER_PASS:                   ${PARITYPR_PASS}
-  # rules:
-  #   - if: $CI_PIPELINE_SOURCE == "schedule"
-  #   - if: $CI_COMMIT_REF_NAME == "master"
-  #   - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
-  #   - if: $CI_COMMIT_REF_NAME == "rococo-v1"
-    #   variables:
-    #     IMAGE_NAME:                docker.io/parity/rococo
-    #     DOCKER_USER:               ${Docker_Hub_User_Parity}
-    #     DOCKER_PASS:               ${Docker_Hub_Pass_Parity}
-  # needs:
-  #   - job:                         build-real-overseer
-  #     artifacts:                   true
+# publish-real-overseer-image:
+# #   image to be tested with Simnet
+#   stage:                           build
+#   <<:                              *build-push-image
+#   variables:
+#     IMAGE_NAME:                    docker.io/paritypr/synth-wave
+#     DOCKER_USER:                   ${PARITYPR_USER}
+#     DOCKER_PASS:                   ${PARITYPR_PASS}
+#   # rules:
+#   #   - if: $CI_PIPELINE_SOURCE == "schedule"
+#   #   - if: $CI_COMMIT_REF_NAME == "master"
+#   #   - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
+#   #   - if: $CI_COMMIT_REF_NAME == "rococo-v1"
+#     #   variables:
+#     #     IMAGE_NAME:                docker.io/parity/rococo
+#     #     DOCKER_USER:               ${Docker_Hub_User_Parity}
+#     #     DOCKER_PASS:               ${Docker_Hub_Pass_Parity}
+#   # needs:
+#   #   - job:                         build-real-overseer
+#   #     artifacts:                   true
 
-publish-adder-collator-image:
-    # service image for Simnet
-  stage:                           build
-  <<:                              *build-push-image
-  variables:
-    # scripts/docker/collator.Dockerfile
-    DOCKERFILE:                    collator.Dockerfile
-    IMAGE_NAME:                    docker.io/paritypr/colander
-    DOCKER_USER:                   ${PARITYPR_USER}
-    DOCKER_PASS:                   ${PARITYPR_PASS}
-  # needs:
-  #   - job:                         build-adder-collator
-  #     artifacts:                   true
-  after_script:
-    # - buildah logout "$IMAGE_NAME"
-    - echo "COLLATOR_IMAGE_TAG=$(cat ./artifacts/EXTRATAG)" > ./artifacts/collator.env
-    - cat ./artifacts/collator.env
-  artifacts:
-    reports:
-      # this artifact is used in trigger-simnet job
-      # https://docs.gitlab.com/ee/ci/multi_project_pipelines.html#with-variable-inheritance
-      dotenv: ./artifacts/collator.env
+# publish-adder-collator-image:
+#     # service image for Simnet
+#   stage:                           build
+#   <<:                              *build-push-image
+#   variables:
+#     # scripts/docker/collator.Dockerfile
+#     DOCKERFILE:                    collator.Dockerfile
+#     IMAGE_NAME:                    docker.io/paritypr/colander
+#     DOCKER_USER:                   ${PARITYPR_USER}
+#     DOCKER_PASS:                   ${PARITYPR_PASS}
+#   # needs:
+#   #   - job:                         build-adder-collator
+#   #     artifacts:                   true
+#   after_script:
+#     # - buildah logout "$IMAGE_NAME"
+#     - echo "COLLATOR_IMAGE_TAG=$(cat ./artifacts/EXTRATAG)" > ./artifacts/collator.env
+#     - cat ./artifacts/collator.env
+#   artifacts:
+#     reports:
+#       # this artifact is used in trigger-simnet job
+#       # https://docs.gitlab.com/ee/ci/multi_project_pipelines.html#with-variable-inheritance
+#       dotenv: ./artifacts/collator.env
 
 
 #### stage:                        publish
